version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./SSL:/SSL

  redis:
    build:
      context: ./redis
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=Wei891013

  redis_backup:
    build:
      context: redis_backup
    volumes:
      - redis_backup_volume:/backup
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=Wei891013

  mysql:
    build:
      context: ./my_sql
    volumes:
      - my_sql_data:/var/lib/mysql
      - ./SSL:/SSL
    environment:
      - MYSQL_ROOT_PASSWORD=Wei891013
      - DATABASE_NAME=sqldb
      - DATABASE_USER=wei
      - DATABASE_PASS=Wei891013

  my_sql_backup:
    build:
      context: my_sql_backup
    volumes:
      - my_sql_backup_volume:/backup
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Wei891013
      MYSQL_DATABASE: sqldb
    depends_on:
      - mysql


  flask:
    build:
      context: ./Back_end_Flask_Server
    environment:
      - JWT_SECRET_KEY=Wei891013
      - SQL_USER=wei
      - SQL_PWD=Wei891013
      - DB_NAME=sqldb
      - EXPIRE_DAYS=14
      - GOOGLE_CLIENT_ID=1076466057181-t43acfts96fnberfng5b9ncur8uaefjt.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - SECRET_KEY=Wei891013
      - REDIS_PASSWORD=Wei891013
      - PAGE_NUMBER=10
    depends_on:
      - nginx
      - mysql
      - redis
    volumes:
      - original_audio:/original_audio
      - original_graph:/original_graph
      - ./Security:/Security
  celery:
    build:
      context: ./celery
    environment:
      - SQL_USER=wei
      - SQL_PWD=Wei891013
      - DB_NAME=sqldb
      - USER_MAIL=open891013@gmail.com
      - USER_PWD=sbdxfzkmaxtesqec
      - REDIS_PASSWORD=Wei891013
    volumes:
      - original_audio:/original_audio
      - original_graph:/original_graph
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]

volumes:
  my_sql_data:
  my_sql_backup_volume:
  redis_data:
  redis_backup_volume:
  original_audio:
  original_graph: