version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./SSL:/SSL

  redis:
    build:
      context: ./redis
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=Wei891013

  redis_backup:
    build:
      context: redis_backup
    volumes:
      - redis_backup_volume:/backup
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=Wei891013

  mysql:
    build:
      context: ./my_sql
    volumes:
      - my_sql_data:/var/lib/mysql
      - ./SSL:/SSL
    environment:
      - MYSQL_ROOT_PASSWORD=Wei891013
      - DATABASE_NAME=sqldb
      - DATABASE_USER=wei
      - DATABASE_PASS=Wei891013

  my_sql_backup:
    build:
      context: my_sql_backup
    volumes:
      - my_sql_backup_volume:/backup
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Wei891013
      MYSQL_DATABASE: sqldb
    depends_on:
      - mysql


  flask:
    build:
      context: ./Back_end_Flask_Server
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=wei
      - MYSQL_PASSWORD=Wei891013
      - MYSQL_DB=sqldb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Wei891013
      - REDIS_DB=0
      - JWT_SECRET=Wei891013
      - JWT_EXPIRE_DAYS=14
      - PAGE_SIZE=10
      - GOOGLE_CLIENT_ID=1076466057181-t43acfts96fnberfng5b9ncur8uaefjt.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - GOOGLE_SESSION_SECRET=Wei891013
      - DIRECTORY_AUDIO=/original_audio
      - DIRECTORY_GRAPH=/original_graph
    depends_on:
      - nginx
      - mysql
      - redis
    volumes:
      - original_audio:/original_audio
      - original_graph:/original_graph
  celery:
    build:
      context: ./celery
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=wei
      - MYSQL_PASSWORD=Wei891013
      - MYSQL_DB=sqldb
      - MAIL_USER=open891013@gmail.com
      - MAIL_PASSWORD=sbdxfzkmaxtesqec
      - REDIS_PASSWORD=Wei891013
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - original_audio:/original_audio
      - original_graph:/original_graph
      - ./Security:/Security
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]

volumes:
  my_sql_data:
  my_sql_backup_volume:
  redis_data:
  redis_backup_volume:
  original_audio:
  original_graph: